// In-memory sliding-window rate limiting for MCP tool calls.
//
// The HTTP routes under /mcp are generated by @lovable.dev/mcp-js and must stay
// untouched, so the limit is enforced in the tool layer instead — every tool
// calls `mcpRateLimitExceeded` before it touches data. Per worker instance,
// which is enough to blunt scripted probing/abuse on top of OAuth + RLS.

const WINDOW_MS = 60_000;
const MAX_CALLS = 30;
const hits = new Map<string, number[]>();

/** Returns true when this caller is over budget for the current window. */
export function mcpRateLimitExceeded(key: string): boolean {
  const now = Date.now();
  const recent = (hits.get(key) ?? []).filter((t) => now - t < WINDOW_MS);

  if (recent.length >= MAX_CALLS) {
    hits.set(key, recent);
    return true;
  }

  recent.push(now);
  hits.set(key, recent);
  if (hits.size > 5000) hits.clear();
  return false;
}

export const MCP_RATE_LIMIT_MESSAGE =
  "Too many requests. Please wait a minute and try again.";
