/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as BecomeAnInstructorRouteImport } from './routes/become-an-instructor'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DownloadAppRouteImport } from './routes/download-app'
import { Route as EarningcalcRouteImport } from './routes/earningcalc'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Offer99RouteImport } from './routes/offer99'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SubscribedRouteImport } from './routes/subscribed'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiCreateSubscriptionRouteImport } from './routes/api/create-subscription'
import { Route as ApiSwitchPlanRouteImport } from './routes/api/switch-plan'
import { Route as ApiVerifySubscriptionRouteImport } from './routes/api/verify-subscription'
import { Route as ApiWatchAccessRouteImport } from './routes/api/watch-access'
import { Route as ApiWatchScheduleRouteImport } from './routes/api/watch-schedule'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicWatchUpcomingRouteImport } from './routes/api/public/watch-upcoming'
import { Route as ApiPublicCronAlertMismatchesRouteImport } from './routes/api/public/cron/alert-mismatches'
import { Route as ApiPublicCronCheckClassVideoRouteImport } from './routes/api/public/cron/check-class-video'
import { Route as ApiPublicHooksRazorpayRouteImport } from './routes/api/public/hooks/razorpay'
import { Route as ApiPublicHooksRazorpaySubscriptionRouteImport } from './routes/api/public/hooks/razorpay-subscription'
import { Route as ApiPublicHooksSyncInstructorApplicationRouteImport } from './routes/api/public/hooks/sync-instructor-application'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAnInstructorRoute = BecomeAnInstructorRouteImport.update({
  id: '/become-an-instructor',
  path: '/become-an-instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadAppRoute = DownloadAppRouteImport.update({
  id: '/download-app',
  path: '/download-app',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningcalcRoute = EarningcalcRouteImport.update({
  id: '/earningcalc',
  path: '/earningcalc',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Offer99Route = Offer99RouteImport.update({
  id: '/offer99',
  path: '/offer99',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribedRoute = SubscribedRouteImport.update({
  id: '/subscribed',
  path: '/subscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCreateSubscriptionRoute = ApiCreateSubscriptionRouteImport.update({
  id: '/api/create-subscription',
  path: '/api/create-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwitchPlanRoute = ApiSwitchPlanRouteImport.update({
  id: '/api/switch-plan',
  path: '/api/switch-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifySubscriptionRoute = ApiVerifySubscriptionRouteImport.update({
  id: '/api/verify-subscription',
  path: '/api/verify-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchAccessRoute = ApiWatchAccessRouteImport.update({
  id: '/api/watch-access',
  path: '/api/watch-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchScheduleRoute = ApiWatchScheduleRouteImport.update({
  id: '/api/watch-schedule',
  path: '/api/watch-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWatchUpcomingRoute = ApiPublicWatchUpcomingRouteImport.update({
  id: '/api/public/watch-upcoming',
  path: '/api/public/watch-upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAlertMismatchesRoute =
  ApiPublicCronAlertMismatchesRouteImport.update({
    id: '/api/public/cron/alert-mismatches',
    path: '/api/public/cron/alert-mismatches',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCheckClassVideoRoute =
  ApiPublicCronCheckClassVideoRouteImport.update({
    id: '/api/public/cron/check-class-video',
    path: '/api/public/cron/check-class-video',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRazorpayRoute = ApiPublicHooksRazorpayRouteImport.update({
  id: '/api/public/hooks/razorpay',
  path: '/api/public/hooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRazorpaySubscriptionRoute =
  ApiPublicHooksRazorpaySubscriptionRouteImport.update({
    id: '/api/public/hooks/razorpay-subscription',
    path: '/api/public/hooks/razorpay-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncInstructorApplicationRoute =
  ApiPublicHooksSyncInstructorApplicationRouteImport.update({
    id: '/api/public/hooks/sync-instructor-application',
    path: '/api/public/hooks/sync-instructor-application',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/become-an-instructor': typeof BecomeAnInstructorRoute
  '/download': typeof DownloadRoute
  '/download-app': typeof DownloadAppRoute
  '/earningcalc': typeof EarningcalcRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/offer99': typeof Offer99Route
  '/pay': typeof PayRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/subscribed': typeof SubscribedRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/watch': typeof WatchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/create-subscription': typeof ApiCreateSubscriptionRoute
  '/api/switch-plan': typeof ApiSwitchPlanRoute
  '/api/verify-subscription': typeof ApiVerifySubscriptionRoute
  '/api/watch-access': typeof ApiWatchAccessRoute
  '/api/watch-schedule': typeof ApiWatchScheduleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/watch-upcoming': typeof ApiPublicWatchUpcomingRoute
  '/api/public/cron/alert-mismatches': typeof ApiPublicCronAlertMismatchesRoute
  '/api/public/cron/check-class-video': typeof ApiPublicCronCheckClassVideoRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/razorpay-subscription': typeof ApiPublicHooksRazorpaySubscriptionRoute
  '/api/public/hooks/sync-instructor-application': typeof ApiPublicHooksSyncInstructorApplicationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/become-an-instructor': typeof BecomeAnInstructorRoute
  '/download': typeof DownloadRoute
  '/download-app': typeof DownloadAppRoute
  '/earningcalc': typeof EarningcalcRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/offer99': typeof Offer99Route
  '/pay': typeof PayRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/subscribed': typeof SubscribedRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/watch': typeof WatchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/create-subscription': typeof ApiCreateSubscriptionRoute
  '/api/switch-plan': typeof ApiSwitchPlanRoute
  '/api/verify-subscription': typeof ApiVerifySubscriptionRoute
  '/api/watch-access': typeof ApiWatchAccessRoute
  '/api/watch-schedule': typeof ApiWatchScheduleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/watch-upcoming': typeof ApiPublicWatchUpcomingRoute
  '/api/public/cron/alert-mismatches': typeof ApiPublicCronAlertMismatchesRoute
  '/api/public/cron/check-class-video': typeof ApiPublicCronCheckClassVideoRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/razorpay-subscription': typeof ApiPublicHooksRazorpaySubscriptionRoute
  '/api/public/hooks/sync-instructor-application': typeof ApiPublicHooksSyncInstructorApplicationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/become-an-instructor': typeof BecomeAnInstructorRoute
  '/download': typeof DownloadRoute
  '/download-app': typeof DownloadAppRoute
  '/earningcalc': typeof EarningcalcRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/offer99': typeof Offer99Route
  '/pay': typeof PayRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/subscribed': typeof SubscribedRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/watch': typeof WatchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/create-subscription': typeof ApiCreateSubscriptionRoute
  '/api/switch-plan': typeof ApiSwitchPlanRoute
  '/api/verify-subscription': typeof ApiVerifySubscriptionRoute
  '/api/watch-access': typeof ApiWatchAccessRoute
  '/api/watch-schedule': typeof ApiWatchScheduleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/watch-upcoming': typeof ApiPublicWatchUpcomingRoute
  '/api/public/cron/alert-mismatches': typeof ApiPublicCronAlertMismatchesRoute
  '/api/public/cron/check-class-video': typeof ApiPublicCronCheckClassVideoRoute
  '/api/public/hooks/razorpay': typeof ApiPublicHooksRazorpayRoute
  '/api/public/hooks/razorpay-subscription': typeof ApiPublicHooksRazorpaySubscriptionRoute
  '/api/public/hooks/sync-instructor-application': typeof ApiPublicHooksSyncInstructorApplicationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/become-an-instructor'
    | '/download'
    | '/download-app'
    | '/earningcalc'
    | '/manage'
    | '/mcp'
    | '/offer99'
    | '/pay'
    | '/payment-failed'
    | '/privacy'
    | '/refund'
    | '/security'
    | '/sitemap.xml'
    | '/subscribe'
    | '/subscribed'
    | '/terms'
    | '/thank-you'
    | '/watch'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/create-subscription'
    | '/api/switch-plan'
    | '/api/verify-subscription'
    | '/api/watch-access'
    | '/api/watch-schedule'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/watch-upcoming'
    | '/api/public/cron/alert-mismatches'
    | '/api/public/cron/check-class-video'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/razorpay-subscription'
    | '/api/public/hooks/sync-instructor-application'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/become-an-instructor'
    | '/download'
    | '/download-app'
    | '/earningcalc'
    | '/manage'
    | '/mcp'
    | '/offer99'
    | '/pay'
    | '/payment-failed'
    | '/privacy'
    | '/refund'
    | '/security'
    | '/sitemap.xml'
    | '/subscribe'
    | '/subscribed'
    | '/terms'
    | '/thank-you'
    | '/watch'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/create-subscription'
    | '/api/switch-plan'
    | '/api/verify-subscription'
    | '/api/watch-access'
    | '/api/watch-schedule'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/watch-upcoming'
    | '/api/public/cron/alert-mismatches'
    | '/api/public/cron/check-class-video'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/razorpay-subscription'
    | '/api/public/hooks/sync-instructor-application'
  id:
    | '__root__'
    | '/'
    | '/account-deletion'
    | '/become-an-instructor'
    | '/download'
    | '/download-app'
    | '/earningcalc'
    | '/manage'
    | '/mcp'
    | '/offer99'
    | '/pay'
    | '/payment-failed'
    | '/privacy'
    | '/refund'
    | '/security'
    | '/sitemap.xml'
    | '/subscribe'
    | '/subscribed'
    | '/terms'
    | '/thank-you'
    | '/watch'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/create-subscription'
    | '/api/switch-plan'
    | '/api/verify-subscription'
    | '/api/watch-access'
    | '/api/watch-schedule'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/watch-upcoming'
    | '/api/public/cron/alert-mismatches'
    | '/api/public/cron/check-class-video'
    | '/api/public/hooks/razorpay'
    | '/api/public/hooks/razorpay-subscription'
    | '/api/public/hooks/sync-instructor-application'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  BecomeAnInstructorRoute: typeof BecomeAnInstructorRoute
  DownloadRoute: typeof DownloadRoute
  DownloadAppRoute: typeof DownloadAppRoute
  EarningcalcRoute: typeof EarningcalcRoute
  ManageRoute: typeof ManageRoute
  McpRoute: typeof McpRoute
  Offer99Route: typeof Offer99Route
  PayRoute: typeof PayRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscribeRoute: typeof SubscribeRoute
  SubscribedRoute: typeof SubscribedRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  WatchRoute: typeof WatchRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiCreateSubscriptionRoute: typeof ApiCreateSubscriptionRoute
  ApiSwitchPlanRoute: typeof ApiSwitchPlanRoute
  ApiVerifySubscriptionRoute: typeof ApiVerifySubscriptionRoute
  ApiWatchAccessRoute: typeof ApiWatchAccessRoute
  ApiWatchScheduleRoute: typeof ApiWatchScheduleRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicWatchUpcomingRoute: typeof ApiPublicWatchUpcomingRoute
  ApiPublicCronAlertMismatchesRoute: typeof ApiPublicCronAlertMismatchesRoute
  ApiPublicCronCheckClassVideoRoute: typeof ApiPublicCronCheckClassVideoRoute
  ApiPublicHooksRazorpayRoute: typeof ApiPublicHooksRazorpayRoute
  ApiPublicHooksRazorpaySubscriptionRoute: typeof ApiPublicHooksRazorpaySubscriptionRoute
  ApiPublicHooksSyncInstructorApplicationRoute: typeof ApiPublicHooksSyncInstructorApplicationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-an-instructor': {
      id: '/become-an-instructor'
      path: '/become-an-instructor'
      fullPath: '/become-an-instructor'
      preLoaderRoute: typeof BecomeAnInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-app': {
      id: '/download-app'
      path: '/download-app'
      fullPath: '/download-app'
      preLoaderRoute: typeof DownloadAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earningcalc': {
      id: '/earningcalc'
      path: '/earningcalc'
      fullPath: '/earningcalc'
      preLoaderRoute: typeof EarningcalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer99': {
      id: '/offer99'
      path: '/offer99'
      fullPath: '/offer99'
      preLoaderRoute: typeof Offer99RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribed': {
      id: '/subscribed'
      path: '/subscribed'
      fullPath: '/subscribed'
      preLoaderRoute: typeof SubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-subscription': {
      id: '/api/create-subscription'
      path: '/api/create-subscription'
      fullPath: '/api/create-subscription'
      preLoaderRoute: typeof ApiCreateSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/switch-plan': {
      id: '/api/switch-plan'
      path: '/api/switch-plan'
      fullPath: '/api/switch-plan'
      preLoaderRoute: typeof ApiSwitchPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-subscription': {
      id: '/api/verify-subscription'
      path: '/api/verify-subscription'
      fullPath: '/api/verify-subscription'
      preLoaderRoute: typeof ApiVerifySubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch-access': {
      id: '/api/watch-access'
      path: '/api/watch-access'
      fullPath: '/api/watch-access'
      preLoaderRoute: typeof ApiWatchAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch-schedule': {
      id: '/api/watch-schedule'
      path: '/api/watch-schedule'
      fullPath: '/api/watch-schedule'
      preLoaderRoute: typeof ApiWatchScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/watch-upcoming': {
      id: '/api/public/watch-upcoming'
      path: '/api/public/watch-upcoming'
      fullPath: '/api/public/watch-upcoming'
      preLoaderRoute: typeof ApiPublicWatchUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/alert-mismatches': {
      id: '/api/public/cron/alert-mismatches'
      path: '/api/public/cron/alert-mismatches'
      fullPath: '/api/public/cron/alert-mismatches'
      preLoaderRoute: typeof ApiPublicCronAlertMismatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check-class-video': {
      id: '/api/public/cron/check-class-video'
      path: '/api/public/cron/check-class-video'
      fullPath: '/api/public/cron/check-class-video'
      preLoaderRoute: typeof ApiPublicCronCheckClassVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/razorpay': {
      id: '/api/public/hooks/razorpay'
      path: '/api/public/hooks/razorpay'
      fullPath: '/api/public/hooks/razorpay'
      preLoaderRoute: typeof ApiPublicHooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/razorpay-subscription': {
      id: '/api/public/hooks/razorpay-subscription'
      path: '/api/public/hooks/razorpay-subscription'
      fullPath: '/api/public/hooks/razorpay-subscription'
      preLoaderRoute: typeof ApiPublicHooksRazorpaySubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-instructor-application': {
      id: '/api/public/hooks/sync-instructor-application'
      path: '/api/public/hooks/sync-instructor-application'
      fullPath: '/api/public/hooks/sync-instructor-application'
      preLoaderRoute: typeof ApiPublicHooksSyncInstructorApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  BecomeAnInstructorRoute: BecomeAnInstructorRoute,
  DownloadRoute: DownloadRoute,
  DownloadAppRoute: DownloadAppRoute,
  EarningcalcRoute: EarningcalcRoute,
  ManageRoute: ManageRoute,
  McpRoute: McpRoute,
  Offer99Route: Offer99Route,
  PayRoute: PayRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscribeRoute: SubscribeRoute,
  SubscribedRoute: SubscribedRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  WatchRoute: WatchRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiCreateSubscriptionRoute: ApiCreateSubscriptionRoute,
  ApiSwitchPlanRoute: ApiSwitchPlanRoute,
  ApiVerifySubscriptionRoute: ApiVerifySubscriptionRoute,
  ApiWatchAccessRoute: ApiWatchAccessRoute,
  ApiWatchScheduleRoute: ApiWatchScheduleRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicWatchUpcomingRoute: ApiPublicWatchUpcomingRoute,
  ApiPublicCronAlertMismatchesRoute: ApiPublicCronAlertMismatchesRoute,
  ApiPublicCronCheckClassVideoRoute: ApiPublicCronCheckClassVideoRoute,
  ApiPublicHooksRazorpayRoute: ApiPublicHooksRazorpayRoute,
  ApiPublicHooksRazorpaySubscriptionRoute:
    ApiPublicHooksRazorpaySubscriptionRoute,
  ApiPublicHooksSyncInstructorApplicationRoute:
    ApiPublicHooksSyncInstructorApplicationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
